In [3]:
import numpy as np

In [1]:
data1 = [6, 7.5, 8, 0, 1]

In [4]:
arr1 = np.array(data1)
arr1

array([ 6. ,  7.5,  8. ,  0. ,  1. ])

In [5]:
data2 = [[1,2,3,4], [5,6,7,8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [6]:
arr2.ndim

2

In [7]:
arr2.shape

(2, 4)

In [8]:
arr1.dtype
arr2.dtype

dtype('int64')

In [9]:
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [10]:
np.zeros((3,6))

array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])

In [13]:
arr3 = np.empty((2,3,2))
arr3

array([[[  0.00000000e+000,  -1.49166824e-154],
        [  2.96439388e-323,   0.00000000e+000],
        [  0.00000000e+000,   0.00000000e+000]],

       [[  0.00000000e+000,   0.00000000e+000],
        [  1.48219694e-323,   0.00000000e+000],
        [  0.00000000e+000,   8.34402697e-309]]])

In [14]:
arr3.ndim

3